### ISSUE TITLE
Errors reading pyarrow.dataset() multiple times against the same path without resetting my Jupyter kernel

### ISSUE THREAD

**Issue by ldacey** [dask/adlfs#167]
**What happened**:
I run into FileNotFound errors when reading the same dataset twice without resetting my kernel in Jupyter. This error occurs if I use fs.info() before reading the dataset as well, as show in the logs below:

 I raised a similar issue here:
https://issues.apache.org/jira/browse/ARROW-11250

**What you expected to happen**:
fs.info() should not impact reading a dataset on the same path, and running ds.dataset() multiple times should not result in a file not found error.

**Minimal Complete Verifiable Example**:

```python
selected_files1 = fs.find("dev/test-split", maxdepth=None, withdirs=True, detail=True)
selected_files2 = fs.find("dev/test-split", maxdepth=None, withdirs=True, detail=True)
selected_files1 == selected_files2

True

#Now when I use fs.info() without a final slash:

fs.info("dev/test-split")
{'name': 'dev/test-split/', 'size': 0, 'type': 'directory'}

#If I add a slash to the folder name, the slash is removed in the fs.info() return - will this impact anything? 

fs.info("dev/test-split/")
{'name': 'dev/test-split', 'size': 0, 'type': 'directory'}
```

Using fs.info() before ds.dataset() causes my dataset to fail to read as well. The error message seems to be different based on whether my source path has a "/" at the end of it or not.

Error with the "/":

```python

[2021-01-15 15:51:47,158] INFO - Reading /dev/case-history/
[2021-01-15 15:51:55,607] INFO - 9682 #print of len(fs.find(input_path, maxdepth=None, withdirs=True, detail=True))
[2021-01-15 15:51:55,892] INFO - {'name': '/dev/case-history', 'size': 0, 'type': 'directory'}
[2021-01-15 15:51:55,893] {taskinstance.py:1150} ERROR - '/dev/case-history/'
Traceback (most recent call last):
...
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 671, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 428, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 395, in _ensure_single_source
    file_info = filesystem.get_file_info([path])[0]
  File "pyarrow/_fs.pyx", line 434, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1012, in pyarrow._fs._cb_get_file_info_vector
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/fs.py", line 195, in get_file_info
    info = self.fs.info(path)
  File "/opt/conda/lib/python3.7/site-packages/adlfs/spec.py", line 522, in info
    fetch_from_azure = (path and self._ls_from_cache(path) is None) or refresh
  File "/opt/conda/lib/python3.7/site-packages/fsspec/spec.py", line 336, in _ls_from_cache
    return self.dircache[path]
  File "/opt/conda/lib/python3.7/site-packages/fsspec/dircache.py", line 62, in __getitem__
    return self._cache[item]  # maybe raises KeyError
KeyError: '/dev/case-history/'
```

Removing the  "/" at the end of the path results in a different error, but my dataset still fails to read:

```python

[2021-01-15 15:36:25,603] INFO - {'name': '/dev/case-history/', 'size': 0, 'type': 'directory'}
[2021-01-15 15:36:25,604] ERROR - /dev/case-history
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 671, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 428, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 404, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: /dev/case-history

```

**Anything else we need to know?**:

**Environment**:
pyarrow 2.0
adlfs 0.5.9
fsspec 0.8.5

- Python version: 3.7
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): Conda

**Comment by hayesgb** [comment]
If you pass "refresh=True" to fs.info() does this still occur?

**Comment by ldacey** [comment]
Running fs.info(path, refresh=True) before my ds.dataset() command did not seem to work:

```
        self.log.info(fs.info(input_path, refresh=True))
        dataset = ds.dataset(
            source=input_path,
            format="parquet",
            schema=None,
            partitioning=partitioning,
            exclude_invalid_files=False,
            filesystem=fs,
        )

[2021-01-16 13:31:04,010] INFO - {'name': 'dev/case-history', 'size': 0, 'type': 'directory'}
[2021-01-16 13:31:04,011] ERROR - 'dev/case-history/'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 671, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 428, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/dataset.py", line 395, in _ensure_single_source
    file_info = filesystem.get_file_info([path])[0]
  File "pyarrow/_fs.pyx", line 434, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/_fs.pyx", line 1012, in pyarrow._fs._cb_get_file_info_vector
  File "/opt/conda/lib/python3.7/site-packages/pyarrow/fs.py", line 195, in get_file_info
    info = self.fs.info(path)
  File "/opt/conda/lib/python3.7/site-packages/adlfs/spec.py", line 522, in info
    fetch_from_azure = (path and self._ls_from_cache(path) is None) or refresh
  File "/opt/conda/lib/python3.7/site-packages/fsspec/spec.py", line 336, in _ls_from_cache
    return self.dircache[path]
  File "/opt/conda/lib/python3.7/site-packages/fsspec/dircache.py", line 62, in __getitem__
    return self._cache[item]  # maybe raises KeyError
KeyError: 'dev/case-history/'`
```


```

**Comment by ldacey** [comment]
fs.invalidate_cache() works for me
