### ISSUE TITLE
0.6.3 - Converting pyarrow dataset to table causes warnings and can hang indefinitely

### ISSUE THREAD

**Issue by ldacey** [dask/adlfs#186]
**What happened**:

I am getting warnings while converting pyarrow datasets to tables it seems while running adlfs 0.6.3. Downgrading to 0.5.9 fixes the issue.

It seems like this warning will happen each time, but sometimes the process hangs indefinitely (some of my tasks were just stuck for 4 hours).

```
[2021-02-18 03:53:13,368] WARNING - Exception ignored in: <function AbstractBufferedFile.__del__ at 0x7fa9f0ad4040>
[2021-02-18 03:53:13,368] WARNING - Traceback (most recent call last):
[2021-02-18 03:53:13,368] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/spec.py", line 1538, in __del__
[2021-02-18 03:53:13,368] WARNING -     self.close()
[2021-02-18 03:53:13,369] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/adlfs/spec.py", line 1553, in close
[2021-02-18 03:53:13,369] WARNING -     maybe_sync(self.container_client.close, self)
[2021-02-18 03:53:13,369] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/asyn.py", line 93, in maybe_sync
[2021-02-18 03:53:13,369] WARNING -     return _run_until_done(func(*args, **kwargs))
[2021-02-18 03:53:13,369] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/asyn.py", line 27, in _run_until_done
[2021-02-18 03:53:13,369] WARNING -     asyncio.tasks._unregister_task(task)
[2021-02-18 03:53:13,369] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/_weakrefset.py", line 114, in discard
[2021-02-18 03:53:13,369] WARNING -     self.data.discard(ref(item))
[2021-02-18 03:53:13,369] WARNING - TypeError: cannot create weak reference to 'NoneType' object
[2021-02-18 03:53:13,373] WARNING - /opt/conda/envs/airflow/lib/python3.8/asyncio/events.py:106 RuntimeWarning: coroutine 'AsyncStorageAccountHostsMixin.close' was never awaited
[2021-02-18 03:53:13,373] WARNING - Exception ignored in: <function AbstractBufferedFile.__del__ at 0x7fa9f0ad4040>
[2021-02-18 03:53:13,373] WARNING - Traceback (most recent call last):
[2021-02-18 03:53:13,373] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/spec.py", line 1538, in __del__
[2021-02-18 03:53:13,374] WARNING -     self.close()
[2021-02-18 03:53:13,374] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/adlfs/spec.py", line 1553, in close
[2021-02-18 03:53:13,374] WARNING -     maybe_sync(self.container_client.close, self)
[2021-02-18 03:53:13,374] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/asyn.py", line 93, in maybe_sync
[2021-02-18 03:53:13,374] WARNING -     return _run_until_done(func(*args, **kwargs))
[2021-02-18 03:53:13,374] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/site-packages/fsspec/asyn.py", line 27, in _run_until_done
[2021-02-18 03:53:13,374] WARNING -     asyncio.tasks._unregister_task(task)
[2021-02-18 03:53:13,374] WARNING -   File "/opt/conda/envs/airflow/lib/python3.8/_weakrefset.py", line 114, in discard
[2021-02-18 03:53:13,375] WARNING -     self.data.discard(ref(item))
[2021-02-18 03:53:13,375] WARNING - TypeError: cannot create weak reference to 'NoneType' object
```

**What you expected to happen**:

**Minimal Complete Verifiable Example**:
This example got stuck indefinitely during the final.to_table() step.

```python
final = ds.dataset("staging/changes", filesystem=fs, partitioning=ds.partitioning(pa.schema([("month_id", pa.int32())]), flavor="hive"))
existing_wids = final.to_table(columns=["employee_wid"]).to_pydict().get("employee_wid")
```

**Anything else we need to know?**:

**Environment**:
```
pyarrow 3.0.0
fsspec 0.8.5
adlfs v0.6.3
logging 0.5.1.2
pandas 1.2.2
numpy 1.20.1
turbodbc 4.1.2
adal 1.2.6
```

- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): Conda

**Comment by jorisvandenbossche** [comment]
The error seems to come from the async parts of fsspec, with which I am not familiar (so can't provide much help).

When it does succeed (and doesn't hang), is the result then correct?

**Comment by ldacey** [comment]
Yes - I believe so. I did not run into any issues or notifications that the data was wrong. I reverted back to 0.5.9 soon after I noticed my tasks stuck in Airflow though, so I am not able to guarantee that

**Comment by hayesgb** [comment]
Based on our discussion on #137 , I've implemented async close operations for both the AzureBlobFileSystem and AzureBlobFile objects.  The error messages state that the close operation was never awaited, and while it doesn't seem to be a problem often, it may be the cause.  I've pushed this as the asyn_close branch if you'd like to give it a shot.  I would implement this with the parameter `asynchronous = False`

**Comment by ldacey** [comment]
I tested the asyn_close branch but ran into inconsistent results.

`fs = adlfs.AzureBlobFileSystem(protocol="abfs", account_name=name, account_key=key, asynchronous=False)
`

When filtering my large dataset into a pyarrow table:

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 1844, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```

This warning was displayed once but the dataset to table conversion worked:

```
/home/jovyan/.local/lib/python3.8/site-packages/adlfs/spec.py:1808: RuntimeWarning: coroutine 'close_container_client' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

For smaller datasets, it seemed to work fine.

**Comment by hayesgb** [comment]
I believe I've finally tracked down this problem.  Would you mind giving the code in asyn_close another look @ldacey ?

**Comment by ldacey** [comment]
Nice - that seemed to work if I specify asynchronous=False. I was able to write datasets to Azure Blob (no empty files), read those datasets and convert them into a table and pandas dataframe. I was also able to read my large dataset as well now (22,000+ fragments) and convert it to a table which is what always failed/got stuck before.


FYI, if I use asynchronous=True, I get errors across the board (this might be expected):
RuntimeError: There is no current event loop in thread 'Dummy-10'.

**Comment by hayesgb** [comment]
Cool.  I'll merge this into master with #194
