### ISSUE TITLE
possible regression that might break other filesystems

### ISSUE THREAD

**Issue by isidentical** [dask/adlfs#280]
It seems like once the new version installed, filesystems like `gcsfs` can't be imported properly. I'm going to guess the error is related with the latest changes on the entry point logic (https://github.com/dask/adlfs/commit/009c265b2960b081c6d9ffb20a1123e4d8178f15) but currently don't have enough capacity to take a look at what's wrong.

Here is the error;
```
root@86c2d741b8ab:/# pip install fsspec[gs]>=2021.10.0
root@86c2d741b8ab:/# python -c 'import gcsfs'
root@86c2d741b8ab:/# pip install adlfs>=2021.10.0
root@86c2d741b8ab:/# python -c 'import gcsfs'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/gcsfs/__init__.py", line 5, in <module>
    from .core import GCSFileSystem
  File "/usr/local/lib/python3.8/site-packages/gcsfs/core.py", line 1095, in <module>
    class GCSFile(fsspec.spec.AbstractBufferedFile):
AttributeError: 'EntryPoint' object has no attribute 'AbstractBufferedFile'
```

**Comment by hayesgb** [comment]
Thanks @isidentical.  @martindurant — have you observed this behavior with any other projects using entry points, or is this unique to adlfs?

**Comment by martindurant** [comment]
I'm afraid that adlfs seems to be the first implementation to actually use this mechanism - others are directly included in the known_implementations dict.

The error is in fsspec.__init__, which overwrites the module variable `spec` if there are any entry points to process.

You can avoid this with one of the following
```
import fsspec; fsspec.AbstractFileSystem  # it's also imported into the top-level
from fsspec.spec import AbstractFileSystem
```

I also have a fix (link coming), but we should figure out how to release.

**Comment by martindurant** [comment]
https://github.com/intake/filesystem_spec/pull/784
